[[redirects]]
from = "/docs/*"
to = "https://docs.sorteio.com/:splat"
status = 200
force = true
headers = {X-Forwarded-Host = "https://sparkly-sprinkles-7d3ad8.netlify.app/"}

[[redirects]]
from = "/docs"
to = "https://docs.sorteio.com/"
status = 200
force = true
headers = {X-Forwarded-Host = "https://sparkly-sprinkles-7d3ad8.netlify.app/"}